"""Foundation layer: vocabulary, configuration, and input validation.

This package imports nothing from the rest of the library. Every other layer
depends on it, which is what keeps the dependency graph acyclic.
"""

from aidatasetkit.core.arrays import NanPolicy, to_float_array
from aidatasetkit.core.config import KitConfig
from aidatasetkit.core.exceptions import (
    AIDatasetKitError,
    AmbiguousFeatureRoleError,
    AmbiguousModelAliasError,
    AmbiguousTaskError,
    ConfigurationError,
    DomainError,
    DuplicateModelError,
    EmptyDataError,
    IncompatibleModelError,
    InvalidModelParameterError,
    InvalidVisualizationRequest,
    MissingDependencyError,
    MissingOrdinalOrderError,
    MissingValueError,
    ModelError,
    NoUsableFeaturesError,
    NonFiniteValueError,
    NonNumericDataError,
    PredictionValidationError,
    PreprocessingError,
    SchemaError,
    ShapeError,
    TaskError,
    UnknownModelError,
    UnsupportedChartError,
    UnsupportedTaskError,
    ValidationError,
    VisualizationError,
    WorkflowStateError,
)
from aidatasetkit.core.provenance import EnvironmentVersions, capture_environment
from aidatasetkit.core.schema import detect_column_kinds, detect_kind
from aidatasetkit.core.types import (
    INTERPRETABILITY_RANK,
    SUPERVISED_TASKS,
    Backend,
    ColumnKind,
    ColumnKinds,
    Estimator,
    Interpretability,
    PreprocessingProfile,
    ProbabilisticEstimator,
    RunMetadata,
    Severity,
    TargetProfile,
    TaskType,
    jsonable,
)

__all__ = [
    "AIDatasetKitError",
    "AmbiguousFeatureRoleError",
    "AmbiguousModelAliasError",
    "AmbiguousTaskError",
    "Backend",
    "ColumnKind",
    "ColumnKinds",
    "ConfigurationError",
    "DomainError",
    "DuplicateModelError",
    "EmptyDataError",
    "EnvironmentVersions",
    "Estimator",
    "INTERPRETABILITY_RANK",
    "IncompatibleModelError",
    "Interpretability",
    "InvalidModelParameterError",
    "InvalidVisualizationRequest",
    "KitConfig",
    "MissingDependencyError",
    "MissingOrdinalOrderError",
    "MissingValueError",
    "ModelError",
    "NoUsableFeaturesError",
    "NanPolicy",
    "NonFiniteValueError",
    "NonNumericDataError",
    "PredictionValidationError",
    "PreprocessingError",
    "PreprocessingProfile",
    "ProbabilisticEstimator",
    "RunMetadata",
    "SUPERVISED_TASKS",
    "SchemaError",
    "Severity",
    "ShapeError",
    "TargetProfile",
    "TaskError",
    "TaskType",
    "UnknownModelError",
    "UnsupportedChartError",
    "UnsupportedTaskError",
    "ValidationError",
    "VisualizationError",
    "WorkflowStateError",
    "capture_environment",
    "detect_column_kinds",
    "detect_kind",
    "jsonable",
    "to_float_array",
]
