"""Every time the example artifact's identity moved, and exactly why.

The identity is ``config_fingerprint(semantic_dict())`` of the audit_churn
example. It is allowed to move -- the fingerprint exists to report that the
record changed -- but never silently. Each move is a step below, and each step
carries the literal identity on either side of it and a *rollback*: the edit that
undoes that change and nothing else.

What is asserted is that, starting from the committed fixture and undoing the
steps newest first, every rollback reproduces the previous identity exactly. A
step that quietly carried a second change would leave a fingerprint that no
longer matches, and the chain would break at that step, naming it.

The chain runs on the committed fixture, not on a freshly built artifact. The
fixture records pandas dtype names, which differ between pandas majors, so a
rebuilt artifact's identity depends on the environment; the history of what
changed does not. Whether the current code reproduces the fixture is asserted
separately, against the fixture for the running pandas major.

**S9 -- clustering landed.** ``supports_out_of_sample_assignment`` joined
:class:`ModelCapabilities`, and the ``known_limitations`` scope sentence stopped
calling clustering out of scope. Neither was special-cased out of the builder to
keep the old number stable: hiding a capability, or leaving a scope statement the
library has outgrown, to preserve an identity would be arranging the record to
match the fingerprint.

**G0 -- the multicollinearity check.** ``KitConfig`` gained
``multicollinearity_vif_threshold``. Every threshold is recorded under
``config.settings.thresholds``, so the new one is too, and ``config.fingerprint``
-- the digest of ``config.settings`` -- moved with it. No finding changed: the
example has no numeric feature with a VIF at or above 10. The schema version does
not move, because no existing field changed shape or meaning; an artifact written
before this step is recognisable by the absent threshold and by its identity.

**G0 -- cv_folds removed.** The setting was declared, validated and recorded
under ``config.settings.thresholds`` while no code path read it: the package runs
no cross-validation. It is gone from ``KitConfig``, so it is gone from the record,
and ``config.fingerprint`` moved again. Nothing else changed, and the schema
version stays: an artifact that records ``cv_folds`` recorded a value that
steered nothing, which is exactly what this step stops asserting.
"""

from __future__ import annotations

import copy
import json
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

import pandas as pd
import pytest

from aidatasetkit.evidence import canonical_json
from aidatasetkit.evidence.fingerprint import config_fingerprint

EXAMPLE = Path(__file__).resolve().parents[1].parent / "examples" / "audit_churn"

#: The reference fixture: the one every recorded identity was measured on.
REFERENCE_FIXTURE = EXAMPLE / "expected_audit_semantic.json"

#: The scope sentence the artifact carried before clustering was verified.
SCOPE_BEFORE = (
    "Only the classification readiness verdict has been verified end to end. "
    "Regression models and their preprocessing are verified; clustering, time "
    "series, text, and images remain out of scope."
)


def _rollback_s9(semantic: dict) -> None:
    del semantic["model"]["capabilities"]["supports_out_of_sample_assignment"]
    semantic["known_limitations"] = [
        SCOPE_BEFORE if entry.startswith("Only the classification") else entry
        for entry in semantic["known_limitations"]
    ]


def _restore_threshold(name: str, value: object) -> Callable[[dict], None]:
    """Undo the removal of one recorded threshold, and nothing else."""

    def rollback(semantic: dict) -> None:
        settings = semantic["config"]["settings"]
        settings["thresholds"][name] = value
        semantic["config"]["fingerprint"] = config_fingerprint(settings)

    return rollback


def _rollback_threshold(name: str) -> Callable[[dict], None]:
    """Undo the addition of one recorded threshold, and nothing else.

    ``config.fingerprint`` is recomputed from ``config.settings`` exactly as the
    builder computes it, because it is a digest of those settings and would
    otherwise still describe the newer ones.
    """

    def rollback(semantic: dict) -> None:
        settings = semantic["config"]["settings"]
        del settings["thresholds"][name]
        semantic["config"]["fingerprint"] = config_fingerprint(settings)

    return rollback


@dataclass(frozen=True)
class Step:
    """One recorded move of the identity."""

    name: str
    before: str
    after: str
    rollback: Callable[[dict], None]


#: Oldest first. Each ``before`` is the previous step's ``after``; the literals
#: are kept so a change to the current code cannot quietly move both sides.
#: Regenerated by ``examples/audit_churn/generate_artifacts.py`` on the
#: reference environment.
CHAIN: tuple[Step, ...] = (
    Step(
        "S9 clustering capability and scope sentence",
        before="4d3139d4a04e34bd34243c80d8232475e30edbfe9daa9f660ef2038f37d95bbc",
        after="b8581966475da37125414a12afc3144d6b1468258ff3dcb3149368406b884852",
        rollback=_rollback_s9,
    ),
    Step(
        "G0 multicollinearity_vif_threshold recorded",
        before="b8581966475da37125414a12afc3144d6b1468258ff3dcb3149368406b884852",
        after="1c449f10c3f9b826e6c166522122f77cc602348a349d11b662ddfe540af5f470",
        rollback=_rollback_threshold("multicollinearity_vif_threshold"),
    ),
    Step(
        "G0 cv_folds removed from the recorded configuration",
        before="1c449f10c3f9b826e6c166522122f77cc602348a349d11b662ddfe540af5f470",
        after="0f0fd1d5e9785d46351d7d28dc15d2d4eda4cc7fbc54bf0509a2a76eb3b471a5",
        rollback=_restore_threshold("cv_folds", 5),
    ),
)

#: The identity the committed reference fixture must carry today.
CURRENT = CHAIN[-1].after


def _stored() -> dict:
    return json.loads(REFERENCE_FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def semantic() -> dict:
    import sys

    root = str(EXAMPLE.resolve().parents[1])
    if root not in sys.path:
        sys.path.insert(0, root)
    from examples.audit_churn.generate_artifacts import build_artifact

    return build_artifact(pd.read_csv(EXAMPLE / "train.csv")).semantic_dict()


class TestTheChain:
    def test_every_step_moves_the_identity(self):
        """Otherwise a step is asserting that nothing happened."""
        for step in CHAIN:
            assert step.before != step.after, step.name

    def test_the_steps_are_contiguous(self):
        for earlier, later in zip(CHAIN, CHAIN[1:]):
            assert earlier.after == later.before, later.name

    def test_the_committed_fixture_carries_the_current_identity(self):
        assert config_fingerprint(_stored()) == CURRENT

    def test_undoing_each_step_reproduces_the_identity_before_it(self):
        """A migration that quietly carried something else would be worse than none."""
        semantic = _stored()
        for step in reversed(CHAIN):
            assert config_fingerprint(semantic) == step.after, step.name
            step.rollback(semantic)
            assert config_fingerprint(semantic) == step.before, step.name


class TestTheCurrentCode:
    def test_it_reproduces_the_fixture_for_this_pandas_major(self, semantic):
        from tests.golden import semantic_fixture_path

        stored = json.loads(semantic_fixture_path().read_text(encoding="utf-8"))
        assert config_fingerprint(semantic) == config_fingerprint(stored)

    def test_the_new_fingerprint_is_deterministic(self, semantic):
        """Rebuilt from scratch, twice, and byte-identical both times.

        A fingerprint that moved once is a migration. A fingerprint that moves
        every time is a broken contract, and the difference is worth proving
        rather than assuming.
        """
        import sys

        root = str(EXAMPLE.resolve().parents[1])
        if root not in sys.path:
            sys.path.insert(0, root)
        from examples.audit_churn.generate_artifacts import build_artifact

        frame = pd.read_csv(EXAMPLE / "train.csv")
        again = build_artifact(frame).semantic_dict()
        assert canonical_json(again) == canonical_json(semantic)
        assert config_fingerprint(again) == config_fingerprint(semantic)


class TestS9:
    def test_the_field_is_present_in_the_artifact(self, semantic):
        """The point of the migration: the capability is now on the record."""
        capabilities = semantic["model"]["capabilities"]
        assert capabilities["supports_out_of_sample_assignment"] is False

    def test_the_scope_statement_no_longer_calls_clustering_out_of_scope(
        self, semantic
    ):
        """An artifact travels further than any other document this library writes.

        Leaving it saying clustering is unverified, when six clusterers are held
        to the same executed contracts as the eighteen supervised models, would
        be shipping a false statement to keep a number stable.
        """
        scope = [
            entry
            for entry in semantic["known_limitations"]
            if entry.startswith("Only the classification")
        ]
        assert len(scope) == 1
        sentence = scope[0]
        verified, _, out_of_scope = sentence.partition("remain out of scope")
        assert out_of_scope == "."
        # Clustering has moved from one half of the sentence to the other. The
        # word is still present -- it now says clustering *is* verified -- so
        # asserting its absence would pass for a sentence that never mentioned it.
        assert "clustering models and their preprocessing are verified" in verified
        assert "clustering, time series" not in verified
        # The verdict itself is still classification-only, and that has not been
        # narrowed, because it has not been verified for anything else.
        assert sentence.startswith(
            "Only the classification readiness verdict has been verified end to end."
        )

    def test_the_builder_does_not_hide_the_field_for_supervised_models(self, semantic):
        """No special case, which was an explicit requirement of the change.

        The example audits a logistic regression, for which the answer is a
        trivial ``False`` -- and it is emitted anyway, because a key that appears
        only on clustering rows would make every consumer branch on its absence.
        """
        assert (
            "supports_out_of_sample_assignment"
            in semantic["model"]["capabilities"]
        )
        assert semantic["model"]["task_type"] == "classification"


class TestTheCvFoldsStep:
    def test_the_setting_is_no_longer_recorded(self, semantic):
        assert "cv_folds" not in semantic["config"]["settings"]["thresholds"]

    def test_the_config_fingerprint_describes_the_recorded_settings(self, semantic):
        config = semantic["config"]
        assert config["fingerprint"] == config_fingerprint(config["settings"])


class TestTheMulticollinearityStep:
    def test_the_threshold_is_recorded_with_its_default(self, semantic):
        thresholds = semantic["config"]["settings"]["thresholds"]
        assert thresholds["multicollinearity_vif_threshold"] == 10.0

    def test_the_config_fingerprint_describes_the_recorded_settings(self, semantic):
        config = semantic["config"]
        assert config["fingerprint"] == config_fingerprint(config["settings"])

    def test_no_finding_moved_with_it(self, semantic):
        """Only the recorded configuration changed; the evidence did not."""
        codes = {finding["code"] for finding in semantic["findings"]}
        assert "possible_multicollinearity" not in codes
        assert "multicollinearity_not_assessed" not in codes

    def test_the_schema_version_did_not_move(self, semantic):
        assert semantic["schema_version"] == "1.0"

    def test_an_older_artifact_is_recognisable(self):
        """A reader holding a pre-G0 artifact can tell, from the file alone."""
        older = _stored()
        for step in reversed(CHAIN):
            step.rollback(older)
            if step.name.startswith("G0 multicollinearity"):
                break
        assert "multicollinearity_vif_threshold" not in older["config"]["settings"]["thresholds"]
        assert config_fingerprint(older) != CURRENT
