"""The artifact identity moved when clustering landed, and exactly why.

Two things changed inside ``semantic_dict()``, and no others.

1. ``supports_out_of_sample_assignment`` joined :class:`ModelCapabilities`, and
   that field is inside ``capabilities.to_dict()``, which is inside the model
   evidence. It is emitted for supervised models too, where the answer is a
   trivial ``False``.
2. The ``known_limitations`` entry describing scope stopped saying clustering was
   out of scope, because six clusterers are now held to the same executed
   capability contracts as the eighteen supervised models. This is the second
   time that sentence has been narrowed; S6 did it for regression.

Neither was special-cased out of the artifact builder to keep the old number
stable. Hiding a capability, or leaving a scope statement the library has
outgrown, in order to preserve an identity would be arranging the record to match
the fingerprint -- which is backwards, because the fingerprint exists to report
that the record changed.

What is asserted here is that those two were the *only* changes, that the new
identity is deterministic, and that both values are on record so anyone holding a
stored artifact can tell which side of the change it came from.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

from aidatasetkit.evidence import canonical_json
from aidatasetkit.evidence.fingerprint import config_fingerprint

EXAMPLE = Path(__file__).resolve().parents[1].parent / "examples" / "audit_churn"

#: The example artifact's identity before the field was added. Kept as a literal
#: so that a change to the current code cannot quietly move both sides at once.
FINGERPRINT_BEFORE = "4d3139d4a04e34bd34243c80d8232475e30edbfe9daa9f660ef2038f37d95bbc"

#: And after. Regenerated by ``examples/audit_churn/generate_artifacts.py``.
FINGERPRINT_AFTER = "b8581966475da37125414a12afc3144d6b1468258ff3dcb3149368406b884852"

#: The scope sentence the artifact carried before clustering was verified.
SCOPE_BEFORE = (
    "Only the classification readiness verdict has been verified end to end. "
    "Regression models and their preprocessing are verified; clustering, time "
    "series, text, and images remain out of scope."
)


@pytest.fixture(scope="module")
def semantic() -> dict:
    import sys

    root = str(EXAMPLE.resolve().parents[1])
    if root not in sys.path:
        sys.path.insert(0, root)
    from examples.audit_churn.generate_artifacts import build_artifact

    return build_artifact(pd.read_csv(EXAMPLE / "train.csv")).semantic_dict()


class TestTheMigration:
    def test_the_two_fingerprints_are_different(self):
        """Otherwise this whole file is asserting that nothing happened."""
        assert FINGERPRINT_BEFORE != FINGERPRINT_AFTER

    def test_the_current_code_produces_the_new_fingerprint(self, semantic):
        assert config_fingerprint(semantic) == FINGERPRINT_AFTER

    def test_the_committed_fixture_produces_it_too(self):
        stored = json.loads((EXAMPLE / "expected_audit_semantic.json").read_text())
        assert config_fingerprint(stored) == FINGERPRINT_AFTER

    def test_the_new_fingerprint_is_deterministic(self, semantic):
        """Rebuilt from scratch, twice, and byte-identical both times.

        A fingerprint that moved once is a migration. A fingerprint that moves
        every time is a broken contract, and the difference is worth proving
        rather than assuming.
        """
        import sys

        root = str(EXAMPLE.resolve().parents[1])
        if root not in sys.path:
            sys.path.insert(0, root)
        from examples.audit_churn.generate_artifacts import build_artifact

        frame = pd.read_csv(EXAMPLE / "train.csv")
        again = build_artifact(frame).semantic_dict()
        assert canonical_json(again) == canonical_json(semantic)
        assert config_fingerprint(again) == config_fingerprint(semantic)

    def test_the_field_is_present_in_the_artifact(self, semantic):
        """The point of the migration: the capability is now on the record."""
        capabilities = semantic["model"]["capabilities"]
        assert capabilities["supports_out_of_sample_assignment"] is False

    def test_the_scope_statement_no_longer_calls_clustering_out_of_scope(
        self, semantic
    ):
        """An artifact travels further than any other document this library writes.

        Leaving it saying clustering is unverified, when six clusterers are held
        to the same executed contracts as the eighteen supervised models, would
        be shipping a false statement to keep a number stable.
        """
        scope = [
            entry
            for entry in semantic["known_limitations"]
            if entry.startswith("Only the classification")
        ]
        assert len(scope) == 1
        sentence = scope[0]
        verified, _, out_of_scope = sentence.partition("remain out of scope")
        assert out_of_scope == "."
        # Clustering has moved from one half of the sentence to the other. The
        # word is still present -- it now says clustering *is* verified -- so
        # asserting its absence would pass for a sentence that never mentioned it.
        assert "clustering models and their preprocessing are verified" in verified
        assert "clustering, time series" not in verified
        # The verdict itself is still classification-only, and that has not been
        # narrowed, because it has not been verified for anything else.
        assert sentence.startswith(
            "Only the classification readiness verdict has been verified end to end."
        )

    def test_those_two_changes_are_the_only_things_that_moved(self, semantic):
        """A migration that quietly carried something else would be worse than none.

        The current artifact is reconstructed as it was before S9 -- the one key
        deleted, the one sentence restored -- and the result must reproduce the
        old identity exactly. Anything else that had changed would show up here
        as a fingerprint that still does not match.
        """
        import copy

        rolled_back = copy.deepcopy(semantic)
        del rolled_back["model"]["capabilities"]["supports_out_of_sample_assignment"]
        rolled_back["known_limitations"] = [
            SCOPE_BEFORE if entry.startswith("Only the classification") else entry
            for entry in rolled_back["known_limitations"]
        ]
        assert config_fingerprint(rolled_back) == FINGERPRINT_BEFORE

    def test_the_builder_does_not_hide_the_field_for_supervised_models(self, semantic):
        """No special case, which was an explicit requirement of the change.

        The example audits a logistic regression, for which the answer is a
        trivial ``False`` -- and it is emitted anyway, because a key that appears
        only on clustering rows would make every consumer branch on its absence.
        """
        assert (
            "supports_out_of_sample_assignment"
            in semantic["model"]["capabilities"]
        )
        assert semantic["model"]["task_type"] == "classification"
